### ISSUE TITLE
Can't open image files 

### ISSUE THREAD

**Issue by IAmOrion** [auc0le/JT-Edit#1]
In this example, a fairly basic/simple PNG file 

![hearbeatOFF](https://github.com/auc0le/JT-Edit/assets/3501380/0ffb0c0a-d9b3-405b-a0c7-bb58b56d9297)

```
app.js:315 Uncaught TypeError: Cannot set properties of undefined (setting '0')
    at loadPixelArrayFromImage (app.js:315:34)
    at img.onload (app.js:115:25)
```

```
pixelArray[y][x] = quantizedColor;
```

**Comment by auc0le** [comment]
The import logic currently only works with jpg files.  There is a Sample.jpg file in the sample files\16x96 that can be used to test.  Note that the jpg needs to be the correct resolution for the selected LED panel to load correctly.  The \sample files\ directory contains '3 bit color table for photoshop.act' which can be used in Photoshop to set the correct 3 bit color palette so you can edit in Photoshop without dithering down the road in this tool.

All of that being said, I will look at adding PNG support and I'll leave this item open to track that.
